### ISSUE TITLE
Problem changing working directory / reoccured

### ISSUE THREAD

**Issue by kevinals** [Standouthost/Multicraft#10]
Hi there,

This happens (as the title says)

Folder structure: http://gyazo.com/268ac717872824387c962cb0b5becf68

prepare.sh: http://pastebin.com/8qtrhgqR

The server is running CentOS 6.6 64 bit

Warmest regards,
Kevin

**Comment by Jmainguy** [comment]
That really should have worked. Did you enable prepare.sh in multicraft.conf?

```
[useragent]
## The path to the Multicraft useragent. This program is used in
## multiuser mode to access user files.
## default: bin (-> "baseDir"/bin, same as daemonDir)
userAgentDir = bin
## The executable of the Multicraft useragent. Note that a config
## file with the same name as this setting (plus .conf) will be
## generated next to this file.
## default: launcher (-> "baseDir"/"userAgentDir"/useragent)
userAgentFile = useragent
## The minimum allowed user and group IDs for server users
## default: 100
userAgentMinUid = 100
userAgentMinGid = 100
## The script to run when a server is being prepared. The path is
## relative to the userAgentDir.
## NOTE: This script will be run as the superuser.
## default: empty
userAgentSuperuserPrepare = prepare.sh
```

**Comment by kevinals** [comment]
Where do I find this?

**Comment by Jmainguy** [comment]
/home/minecraft/multicraft/multicraft.conf around line 150, just uncomment the lines that need uncommenting, and add prepare.sh to the userAgentSuperuserPrepare = line. Restart multicraft after editing this file.

**Comment by kevinals** [comment]
That is done aswell.

I think you are talking right now either via skype or something with my staff (Kelvin)

**Comment by kevinals** [comment]
Do you have any other kind of solution? so if other has the error they can try to resolve it

**Comment by Jmainguy** [comment]
Talking with your friend in IRC, it does appear to be the issue I mentioned above in multicraft.conf

**Comment by kevinals** [comment]
I hope that fixes it,

Thanks for the support Jonathan!

**Comment by Jmainguy** [comment]
Yup worked with your friend on IRC and its all working now. It was a combination of the above, and a typo he accidentally made in prepare.sh. All fixed and working now.

**Comment by kevinals** [comment]
Many thanks!
