### ISSUE TITLE
Why don't you include binaries in this/or another parallel repository?

### ISSUE THREAD

**Issue by Leopere** [Standouthost/Multicraft#11]
Github is going to be around likely for a long time after your interests may disappear for MC would you be opposed to putting the binaries in a parallel repo?  Seems that some of them download a bit strangely and don't pass hash checks after the download no matter what machine I use for it.

**Comment by Jmainguy** [comment]
Hey @chamunks 

I originally did include binaries in github, however github used to dissalow binaries over 50MB, and as some of my binaries were larger, I moved all binaries to pulp.

Having the binaries on another repo enables people to clone this repo easily as bandwidth is expensive and having a small repo is great.

I also actually do not do much to these zips to create them. Some of them are stock from original providers, some of them I unzipped, renamed the jar, and rezipped, and some of them are installing the mod in a directory, and the zipping that directory up.

I do not provide md5 hash's for the downloads at https://pulp.soh.re/pulp/isos/multicraft/, what hash checks are you performing / comparing them to?

Which downloads specifically are failing for you?

Also, please feel free to take the binaries and upload them anywhere else you think would be great, thy are also open source and free to distribute as you please.

**Comment by chamunks** [comment]
Theres new restrictions now.  https://help.github.com/articles/distributing-large-binaries/ If its included in a separate repo we could potentially automate this process to some extent idk.  I'd have to stare at this repo a bit more to fully wrap my head around what is exactly going on here.  I've not really seen this in action but my friend says its great.
