### ISSUE TITLE
Please add Imagicalmine.phar.conf

### ISSUE THREAD

**Issue by andris155** [Standouthost/Multicraft#17]
New PE server manager: http://jenkins.imagicalcorp.ml:8080/
Pocketmine build page not working, and not develope new builds.

**Comment by Jmainguy** [comment]
Sounds good, will look into adding this later this week. Will update here once I can reach a decision.

**Comment by andris155** [comment]
https://github.com/ImagicalMine/IM-Multicraft

**Comment by Jmainguy** [comment]
I am unfamiliar with Imagicalmine, so just trying to understand it. Looking at http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine/ seems like they want php7 now, is that your understanding as well? Or am I looking at the wrong thing to download

**Comment by andris155** [comment]
https://github.com/ImagicalMine/IM-Multicraft
Tested, not work :/ Not detect server start, and player joins, and lefts.

**Comment by andris155** [comment]
PHP 7 for imagicalmine: https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries/view
Windows: https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher

**Comment by andris155** [comment]
ImagicalMine update php 5 to php 7 1-2 weeks ago, and download not wrong.
