### ISSUE TITLE
Unzip Issue

### ISSUE THREAD

**Issue by mja00** [Standouthost/Multicraft#21]
The script is never unzipping the modpack zips and it won't work. I have the exact same scripts running on a different daemon and they work perfectly fine but on here they don't. Working machine is running CentOS 6 while the not working one is running CentOS 7. Please fix as soon as possible. http://pastebin.com/y2bUySaV Server 41 is the test server that I'm using to fix the issue.

**Comment by Jmainguy** [comment]
```
2016-03-27 22:46:17,566 DEBUG    server 41: Failed to copy jarfile: [Errno 1] /bin/cp: cannot stat ‘/home/minecraft/multicraft/jar/Dire.jar’: No such file or directory
```
looks like the prepare.sh script is trying to cp Dire.jar and not unzip anything. Not sure why it would do that, its exiting error code 1, which means one of the commands is failing. Do you have zip/unzip installed? 

```
yum install unzip
```
